#!/bin/bash

echo "01. Install XCode command line utilities"
xcode-select --install

echo "02. Install Homebrew"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "03. Install Cask"
brew install cask

echo "04. Give Homebrew greater permissions"
sudo mkdir $(brew --prefix)/include
sudo mkdir $(brew --prefix)/Frameworks
sudo chown -R $(whoami) $(brew --prefix)/*

echo "05. Install many, many Homebrew applications"
brew install git git-flow hub
brew install reattach-to-user-namespace tmux
brew install jq miller p7zip telnet
brew install python
brew install vim --with-override-system-vi --with-python3

echo "06. Install many, many Cask applications"
brew cask install docker
brew cask install filezilla
brew cask install google-chrome
brew cask install iterm2
brew cask install minecraft
brew cask install race-for-the-galaxy
brew cask install slack
brew cask install spotify
brew cask install steam
brew cask install the-unarchiver
brew cask install visual-studio-code

echo "07. Create necessary directories"
mkdir ~/Desktop/Screenshots
mkdir -p ~/Documents/code/documentation
mkdir ~/Documents/code/py

echo "08. Set up global Git config variables"
git config --global user.name "Justin Peterson"
git config --global user.email "justinmpeterson@gmail.com"

echo "09. Clone my dotfiles repo"
git clone https://github.com/justinmpeterson/documentation.git ~/Documents/code/documentation

echo "10. Tell MacOS not to create .DS_Store files on network shares"
defaults write com.apple.desktopservices DSDontWriteNetworkStores true

echo "11. Save screenshots somewhere else"
defaults write com.apple.screencapture location ~/Desktop/Screenshots

echo "12. Symbolic links"
ln -s $HOME/Documents/code/documentation/dotfiles/.bash_profile $HOME/.bash_profile
ln -s $HOME/Documents/code/documentation/dotfiles/.tmux.conf $HOME/.tmux.conf
ln -s $HOME/Documents/code/documentation/dotfiles/.vimrc $HOME/.vimrc

echo "And finally, reset the Finder so my screenshot command takes effect immediately"
killall SystemUIServer
