#!/bin/bash

# Must run this command before this repo can even be cloned on a brand-new Mac:
# xcode-select --install

AWAIT=(read -p "Press any key to continue: " -n 1 -s)

cd ~

echo "01. Create necessary directories"
mkdir ~/Desktop/Screenshots
mkdir -p ~/Documents/workspace
"${AWAIT[@]}" && echo

echo "02. Install Homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
"${AWAIT[@]}" && echo

echo "03. Give Homebrew greater permissions"
# sudo mkdir $(brew --prefix)/include
# sudo mkdir $(brew --prefix)/Frameworks
sudo chown -R $(whoami) $(brew --prefix)/*
"${AWAIT[@]}" && echo

echo "04. Install many, many Homebrew applications"
# aws-sam-cli irssi mysql-client vim coreutils moreutils rtv telnet
brew install git git-flow hub
brew install reattach-to-user-namespace tmux
brew install bash jq miller p7zip speedtest-cli todo-txt
brew install awscli openjdk python terraform
brew install go-jira gopass gnupg pinentry-mac
"${AWAIT[@]}" && echo

echo "05. Install many, many Cask applications"
brew install docker
brew install google-chrome
brew install iterm2
# brew install microsoft-teams
# brew install onedrive
brew install pycharm-ce
# brew install skype-for-business
brew install slack
# brew install sourcetree
brew install the-unarchiver
brew install visual-studio-code
"${AWAIT[@]}" && echo

echo "06. Install Powerline fonts"
cd $HOME/Documents
git clone https://github.com/powerline/fonts.git --depth=1
cd fonts
./install.sh
cd ..
rm -rf fonts
"${AWAIT[@]}" && echo

echo "07. Install oh-my-zsh"
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
"${AWAIT[@]}" && echo

echo "08. Install PowerLevel10k"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
"${AWAIT[@]}" && echo

echo "09. Set up global Git config variables"
git config --global user.name "Justin Peterson"
git config --global user.email "jpeterson@extron.com"
git config --global init.defaultBranch master
"${AWAIT[@]}" && echo

echo "10. Install vimwiki and its documentation"
git clone https://github.com/vimwiki/vimwiki.git ~/.vim/pack/plugins/start/vimwiki
vim -c 'helptags ~/.vim/pack/plugins/start/vimwiki/doc' -c quit
"${AWAIT[@]}" && echo

echo "11. Tell MacOS not to create .DS_Store files on network shares"
defaults write com.apple.desktopservices DSDontWriteNetworkStores true
"${AWAIT[@]}" && echo

echo "12. Save screenshots somewhere else"
defaults write com.apple.screencapture location ~/Desktop/Screenshots
"${AWAIT[@]}" && echo

echo "13. Symbolic links"
ln -s $HOME/.config/new-mac-starter-kit/dotfiles/.bash_profile $HOME/.bash_profile
ln -s $HOME/.config/new-mac-starter-kit/dotfiles/.todo.cfg $HOME/.todo.cfg
ln -s $HOME/.config/new-mac-starter-kit/dotfiles/.tmux.conf $HOME/.tmux.conf
ln -s $HOME/.config/new-mac-starter-kit/dotfiles/.vimrc $HOME/.vimrc
ln -s $HOME/.config/new-mac-starter-kit/dotfiles/.zshrc $HOME/.zshrc
"${AWAIT[@]}" && echo

echo "14. Reset the Finder so my screenshot command takes effect immediately"
killall SystemUIServer
"${AWAIT[@]}" && echo

echo "15. Make ZSH my default shell"
chsh -s /bin/zsh
"${AWAIT[@]}" && echo

echo "16. Add Homebrew Bash to the list of available shells"
echo "/usr/local/bin/bash" | sudo tee -a /etc/shells
"${AWAIT[@]}" && echo

echo "All the automatic work is now done! Manual steps remaining include:"
echo "A. Install VirtualBox"
echo "B. Install Hashicorp's Vagrant"
echo "C. Install the Oracle Instant Client"
echo "D. Install the Forticlient VPN client"
echo "E. Create a GPG key and associate it with your STATS GitHub account."
echo "   + https://statsinc.atlassian.net/wiki/spaces/DEVOPS/pages/923992191/GPG+keys+-+create+and+configure"
