#!/bin/bash

# Must run this command before this repo can even be cloned on a brand-new Mac:
# xcode-select --install

AWAIT=(read -p "Press any key to continue: " -n 1 -s)

cd ~

echo "01. Install Homebrew"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
"${AWAIT[@]}" && echo

echo "02. Update Homebrew and install Cask"
brew update
brew install cask
"${AWAIT[@]}" && echo

echo "03. Give Homebrew greater permissions"
sudo mkdir $(brew --prefix)/include
sudo mkdir $(brew --prefix)/Frameworks
sudo chown -R $(whoami) $(brew --prefix)/*
"${AWAIT[@]}" && echo

echo "04. Install many, many Homebrew applications"
brew install git git-flow hub
brew install reattach-to-user-namespace tmux
brew install bash coreutils jq miller moreutils p7zip rtv speedtest-cli telnet todo-txt
brew install aws-sam-cli awscli irssi mysql-client python vim
"${AWAIT[@]}" && echo

echo "05. Install many, many Cask applications"
brew cask install docker
brew cask install google-chrome
brew cask install iterm2
brew cask install microsoft-teams
brew cask install onedrive
brew cask install pycharm-ce
brew cask install skype-for-business
brew cask install slack
brew cask install sourcetree
brew cask install the-unarchiver
brew cask install visual-studio-code
"${AWAIT[@]}" && echo

echo "06. Install Powerline fonts"
cd $HOME/Documents/code
git clone https://github.com/powerline/fonts.git --depth=1
cd fonts
./install.sh
cd ..
rm -rf fonts
"${AWAIT[@]}" && echo

echo "07. Install oh-my-zsh"
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
"${AWAIT[@]}" && echo

echo "08. Install PowerLevel10k"
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k
"${AWAIT[@]}" && echo

echo "08. Create necessary directories"
mkdir ~/Desktop/Screenshots
mkdir ~/Documents/.logs
mkdir -p ~/Documents/code/py
"${AWAIT[@]}" && echo

echo "09. Set up global Git config variables"
git config --global user.name "Justin Peterson"
git config --global user.email "justin.peterson@statsperform.com"
"${AWAIT[@]}" && echo

echo "10. Install vimwiki"
git clone https://github.com/vimwiki/vimwiki.git ~/.vim/pack/plugins/start/vimwiki
"${AWAIT[@]}" && echo

echo "11. Tell MacOS not to create .DS_Store files on network shares"
defaults write com.apple.desktopservices DSDontWriteNetworkStores true
"${AWAIT[@]}" && echo

echo "12. Save screenshots somewhere else"
defaults write com.apple.screencapture location ~/Desktop/Screenshots
"${AWAIT[@]}" && echo

echo "13. Symbolic links"
ln -s $HOME/Documents/.setup/new-mac-starter-kit/dotfiles/.bash_profile $HOME/.bash_profile
ln -s $HOME/Documents/.setup/new-mac-starter-kit/dotfiles/.tmux.conf $HOME/.tmux.conf
ln -s $HOME/Documents/.setup/new-mac-starter-kit/dotfiles/.vimrc $HOME/.vimrc
ln -s $HOME/Documents/.setup/new-mac-starter-kit/dotfiles/.zshrc $HOME/.zshrc
"${AWAIT[@]}" && echo

echo "14. Reset the Finder so my screenshot command takes effect immediately"
killall SystemUIServer
"${AWAIT[@]}" && echo

echo "15. Make ZSH my default shell"
chsh -s /bin/zsh
"${AWAIT[@]}" && echo

echo "16. Add Homebrew Bash to the list of available shells"
echo "/usr/local/bin/bash" | sudo tee -a /etc/shells
"${AWAIT[@]}" && echo

echo "All the automatic work is now done! Manual steps remaining include:"
echo "A. Install VirtualBox"
echo "B. Install Hashicorp's Vagrant"
echo "C. Install the Oracle Instant Client"
echo "D. Install the Forticlient VPN client"
